#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-constraint
Version  : 1.4.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/37/8b/5f1bc2734ca611943e1d6733ee244238679f6410a10cd45ede55a61a8402/python-constraint-1.4.0.tar.bz2
Source0  : https://files.pythonhosted.org/packages/37/8b/5f1bc2734ca611943e1d6733ee244238679f6410a10cd45ede55a61a8402/python-constraint-1.4.0.tar.bz2
Summary  : python-constraint is a module implementing support for handling CSPs (Constraint Solving Problems) over finite domain
Group    : Development/Tools
License  : BSD-2-Clause
Requires: python-constraint-python = %{version}-%{release}
Requires: python-constraint-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
python-constraint
        =================
        
        Introduction
        ------------

%package python
Summary: python components for the python-constraint package.
Group: Default
Requires: python-constraint-python3 = %{version}-%{release}

%description python
python components for the python-constraint package.


%package python3
Summary: python3 components for the python-constraint package.
Group: Default
Requires: python3-core
Provides: pypi(python_constraint)

%description python3
python3 components for the python-constraint package.


%prep
%setup -q -n python-constraint-1.4.0
cd %{_builddir}/python-constraint-1.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583867096
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
